# Generated by Django 2.0.3 on 2018-03-28 22:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePersonalised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('compute', 'Compute'), ('softwareComponent', 'Software Component'), ('webApplication', 'Web Application')], max_length=250)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('photo', models.FileField(default='img/serveur.jpg', upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersoAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='text', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodePerso.NodePersonalised')),
            ],
        ),
    ]
