# Generated by Django 2.0.3 on 2018-04-02 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodePerso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='nodepersonalised',
            name='type',
        ),
        migrations.AddField(
            model_name='nodepersonalised',
            name='derivedFrom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nodePerso.BaseNode'),
        ),
    ]
