# Generated by Django 2.0.3 on 2018-04-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodePerso', '0003_auto_20180402_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodepersonalised',
            name='derivedFrom',
            field=models.CharField(default='compute', max_length=250, verbose_name='Derived From'),
        ),
        migrations.DeleteModel(
            name='BaseNode',
        ),
    ]
