# Generated by Django 2.0.3 on 2018-04-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createTemplate', '0002_template'),
        ('nodePerso', '0004_auto_20180405_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersoAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='persoattribute',
            name='value',
        ),
        migrations.AlterField(
            model_name='nodepersonalised',
            name='derivedFrom',
            field=models.CharField(choices=[('compute', 'Compute'), ('database', 'Database'), ('dbms', 'DBMS'), ('softwareComponent', 'Software Component'), ('webApplication', 'Web Application'), ('webServer', 'WebServer')], default='compute', max_length=250, verbose_name='Derived From'),
        ),
        migrations.AddField(
            model_name='persoattributevalue',
            name='persoAtt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodePerso.PersoAttribute'),
        ),
        migrations.AddField(
            model_name='persoattributevalue',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createTemplate.Template'),
        ),
    ]
