# Generated by Django 2.0.3 on 2018-04-12 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createTemplate', '0003_auto_20180412_1959'),
        ('nodePerso', '0005_auto_20180406_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodepersonalised',
            name='compute',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='createTemplate.Compute'),
        ),
        migrations.AddField(
            model_name='nodepersonalised',
            name='database',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='createTemplate.Database'),
        ),
        migrations.AddField(
            model_name='nodepersonalised',
            name='softwareComponent',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='createTemplate.SoftwareComponent'),
        ),
        migrations.AddField(
            model_name='nodepersonalised',
            name='webApplication',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='createTemplate.WebApplication'),
        ),
        migrations.AddField(
            model_name='nodepersonalised',
            name='webServer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='createTemplate.WebServer'),
        ),
    ]
