# Generated by Django 2.0.3 on 2018-04-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodePerso', '0007_auto_20180413_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodepersonalised',
            name='compute',
        ),
        migrations.RemoveField(
            model_name='nodepersonalised',
            name='database',
        ),
        migrations.RemoveField(
            model_name='nodepersonalised',
            name='softwareComponent',
        ),
        migrations.RemoveField(
            model_name='nodepersonalised',
            name='webApplication',
        ),
        migrations.RemoveField(
            model_name='nodepersonalised',
            name='webServer',
        ),
    ]
