# Generated by Django 2.0.3 on 2018-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('temps', models.FloatField(default=1000, verbose_name='Response Time')),
                ('cout', models.FloatField(default=100, verbose_name='Cost')),
                ('disp', models.FloatField(default=0.99, verbose_name='Availability')),
                ('lie', models.CharField(choices=[('compute', 'Compute'), ('database', 'Database'), ('dbms', 'DBMS'), ('softwareComponent', 'Software Component'), ('webApplication', 'Web Application'), ('webServer', 'WebServer')], default='compute', max_length=250, verbose_name='For')),
            ],
        ),
    ]
