# Generated by Django 2.0.3 on 2018-03-27 23:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePersonalised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('typen', models.CharField(max_length=250)),
                ('attribute', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('photo', models.FileField(default='{% static "img/serveur.jpg" %}', upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
