# Generated by Django 2.0.3 on 2018-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodepersonalised',
            name='photo',
            field=models.FileField(upload_to='', verbose_name='img/serveur.jpg'),
        ),
    ]
