# Generated by Django 2.0.3 on 2018-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20180328_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodepersonalised',
            name='photo',
            field=models.FileField(default='img/serveur.jpg', upload_to=''),
        ),
    ]
