# Generated by Django 2.0.3 on 2018-03-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_auto_20180328_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersoAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='text', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='nodepersonalised',
            name='attribute',
        ),
        migrations.AddField(
            model_name='persoattribute',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.NodePersonalised'),
        ),
    ]
