# Generated by Django 2.0.3 on 2018-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_auto_20180328_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodepersonalised',
            name='typen',
            field=models.CharField(choices=[('Compute', 'Compute'), ('Software Component', 'Software Component'), ('Web Application', 'Web Application')], max_length=250),
        ),
    ]
