# Generated by Django 2.0.3 on 2018-03-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_auto_20180328_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodepersonalised',
            name='user',
        ),
        migrations.RemoveField(
            model_name='persoattribute',
            name='node',
        ),
        migrations.DeleteModel(
            name='NodePersonalised',
        ),
        migrations.DeleteModel(
            name='PersoAttribute',
        ),
    ]
