# Generated by Django 2.0.3 on 2018-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cpus', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('mem_size', models.IntegerField()),
                ('architecture', models.CharField(max_length=250)),
                ('os_type', models.CharField(max_length=250)),
                ('distribution', models.CharField(max_length=250)),
                ('version', models.FloatField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dbms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_password', models.CharField(max_length=250)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_version', models.FloatField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WebApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_root', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WebServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_version', models.FloatField(max_length=2)),
            ],
        ),
    ]
