# Generated by Django 2.0.3 on 2018-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
            ],
        ),
    ]
