# Generated by Django 2.0.3 on 2018-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTemplate', '0002_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='compute',
            name='name',
            field=models.CharField(default='null', max_length=250, verbose_name='Instance name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='nameInst',
            field=models.CharField(default='null', max_length=250, verbose_name='Instance name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbms',
            name='name',
            field=models.CharField(default='null', max_length=250, verbose_name='Instance name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwarecomponent',
            name='name',
            field=models.CharField(default='null', max_length=250, verbose_name='Instance name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='name',
            field=models.CharField(default='null', max_length=250, verbose_name='Instance name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webserver',
            name='name',
            field=models.CharField(default='null', max_length=250, verbose_name='Instance name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compute',
            name='disk_size',
            field=models.IntegerField(verbose_name='Disk size'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='mem_size',
            field=models.IntegerField(verbose_name='Memory size'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='num_cpus',
            field=models.IntegerField(verbose_name='Number of CPUs'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='os_type',
            field=models.CharField(max_length=250, verbose_name='OS type'),
        ),
    ]
