# Generated by Django 2.0.3 on 2018-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTemplate', '0003_auto_20180412_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute',
            name='disk_size',
            field=models.IntegerField(verbose_name='Disk size (GB)'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='mem_size',
            field=models.IntegerField(verbose_name='Memory size (MB)'),
        ),
    ]
