# Generated by Django 2.0.3 on 2018-04-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphGenerator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compute',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.DeleteModel(
            name='Dbms',
        ),
        migrations.DeleteModel(
            name='SoftwareComponent',
        ),
        migrations.DeleteModel(
            name='WebApplication',
        ),
        migrations.DeleteModel(
            name='WebServer',
        ),
    ]
